### ISSUE TITLE
Module Request: Panasonic AW-RP50 and AW-RP120

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion-module-panasonic-camera-controller#1]
**Describe the feature**
Module for calling preset etc from the camera controller

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
http://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/RP50_120/RemoteControllerInterfaceSpecifications-V1.00E.pdf

https://www.reddit.com/r/crestron/comments/4gfuhn/panasonic_ptz_camera_control_protocol/
**Usecases**
Calling a preset for the remote head doing both lecture and panel.

**Comment by josephdadams** [comment]
Transferred this to the panasonic camera controller repo since it states it supports these models.

**Comment by smayberry** [comment]
@ICE9MOONEY I can try to work this in as time allows.  I only have the RP-50 which does not support recalling camera presets.  Until then, perhaps a work-around for you could be to use the [panasonic-ptz module](https://github.com/bitfocus/companion-module-panasonic-ptz/blob/master/HELP.md) to interact directly with each camera for recalling presets.

**Comment by McHauge** [comment]
closing this as this is now a live module

**Comment by McHauge** [comment]
@SalkinDK , @ICE9MOONEY and @smayberry, I have now implemented what the API allows interms of calling presets and after having borrowed remote access to @reykroona's controller, for testing this, should now work with this module, and in the latest beta's and there are also feedbacks and variables for selected camera/group/port, unfortunately, that is all I can add, due to the API being so limited.
