### ISSUE TITLE
panasonic AW-RP150 ptz controller

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion-module-panasonic-camera-controller#3]
support for the Panasonic AW-RP150 and the AW-RP130 PTZ controller.

New features with these controllers, like timed zoom and pan. (change preset in a given number of seconds.)
would be nice to have this under a button

**Comment by reykroona** [comment]
@McHauge Sounds good, let me know when you are ready and I’ll get it setup for you.

**Comment by McHauge** [comment]
@reykroona Hi again, I feel like I got some time on my hands over the next week or so, would I be possible for you to set up the controller for remote access. then I'll give the module a go.

**Comment by reykroona** [comment]
@McHauge Great, I won't be able to grab it until Wednesday. Once it's online I'll DM you the IP.

**Comment by McHauge** [comment]
@fdebeer, @K9-Tim  and @reykroona, after having borrowed remote access to @reykroona's controller this should unit should now work with this module in the latest beta's and there are also feedbacks and variables for selected camera/group/port, unfortunately, that is all I can add, due to the API being so limited.
